[package]
name = "huj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
  rayon = "1.7.0"
  uint = "0.9.5"